### ISSUE TITLE
Tye 0.1 Release Checklist

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#334]
**Before**

- [x] Walk through samples
- [x] Release Notes
- [x] Package on nuget.org

**After**

- [x] Create release
- [x] Update getting started/samples to point to right versions
- [x] Update instructions for nuget.org
- [x] Update branding in `master` for next version
