### ISSUE TITLE
Tye MVP release checklist

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#4]
**Before**

- [x] Approval for name
- [x] Package Publishing
- [x] Signing
- [x] License
- [x] Copyright headers
- [x] Code of conduct
- [x] CLA
- [x] Survey included with product (update url)
- [x] Package prefix reservations
- [x] Third-party notices (chill with artak)
- [x] Plans for promotion (delay blogpost, just use twitter)

**After**

- [ ] Package on nuget.org
- [x] Update getting started/samples to point to right versions
- [x] Remove access token from redis section (raw content requires a token on private repos)
