### ISSUE TITLE
Tye 0.2 Release Checklist

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#407]
**Before**

- [x] Walk through samples
- [x] Walk through samples on Linux
- [x] Release Notes
- [x] Package on nuget.org

**After**

- [x] Create release
- [x] Update getting started/samples to point to right versions
- [x] Update branding in `master` for next version
