### ISSUE TITLE
Tye 0.3 release checklist

### ISSUE THREAD

**Issue by jkotalik** [dotnet/tye#547]
**Before**

- [x] Walk through samples on Windows
- [x] Walk through samples on Linux
- [x] Release Notes
- [x] Package on nuget.org

**After**

- [x] Create release
- [x] Update getting started/samples to point to right versions
- [x] Update branding in `master` for next version
