### ISSUE TITLE
Tye 0.4 Release checklist

### ISSUE THREAD

**Issue by jkotalik** [dotnet/tye#590]
**Before**

- [x] Walk through samples on Windows
- [x] Walk through samples on Linux
- [x] Verify all new large features
  - [x] Azure functions
- [x] Release Notes
- [x] Package on nuget.org

**After**

- [x] Create release
- [x] Update getting started/samples to point to right versions
- [x] Update branding in `master` for next version
