### ISSUE TITLE
ToDo list with multiple services and AWS X-Ray

### ISSUE THREAD

**Issue by Kralizek** [dotnet/tye#748]
### Some details

To try Tye, I'm working on this multi tier ToDo list: https://github.com/Kralizek/ToDoList

Nothing fancy:
- A web application based on Razor Pages as UI
- A web API application based on ASP.NET Core as entry point in the back-end
- A GRPC service as actual backend (and currently, also data storage with an in-memory provider)

**How many services are in your application? (including things like databases, redis):**

- [ ] 1-2
- [x] 3-5
- [ ] 6-10
- [ ] 10+

**What did you use tye for?**

- [x] Local development
- [ ] Deployment

**How is your code organized?**

- [ ] One service per repo
- [x] Many services in one big repo
- [ ] Other (please explain)

### What did you think of tye?

Everything worked pretty fine but I'm having some issues when adding the AWS X-Ray daemon container to `tye.yml` instead of having the container running on my machine independently (I'd love some help there, because my docker networking understanding is pretty limited).

Here is my `tye.yml` file: https://github.com/Kralizek/ToDoList/blob/master/tye.yaml

Some comments (mostly QoL improvements)
- Add the process ID in the dashboard: since debugging is still a "attach to process"-experience, having the process ID at hand would be really nice
- in the yml file, allow configurations to be shared across all services: e.g. an `env` section that gets passed to all services.
- in the yml file, when specifying volumes, allow usage of environmental variables (like %USERPROFILE% or %HOME%).
